import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        jk: {
          surface: "var(--jk-surface)",
          "surface-dim": "var(--jk-surface-dim)",
          "surface-bright": "var(--jk-surface-bright)",
          "surface-container-lowest": "var(--jk-surface-container-lowest)",
          "surface-container-low": "var(--jk-surface-container-low)",
          "surface-container": "var(--jk-surface-container)",
          "surface-container-high": "var(--jk-surface-container-high)",
          "surface-container-highest": "var(--jk-surface-container-highest)",
          "surface-variant": "var(--jk-surface-variant)",
          "surface-tint": "var(--jk-surface-tint)",
          "on-surface": "var(--jk-on-surface)",
          "on-surface-variant": "var(--jk-on-surface-variant)",
          "on-background": "var(--jk-on-background)",
          primary: "var(--jk-primary)",
          "primary-container": "var(--jk-primary-container)",
          "on-primary": "var(--jk-on-primary)",
          "on-primary-container": "var(--jk-on-primary-container)",
          secondary: "var(--jk-secondary)",
          "secondary-container": "var(--jk-secondary-container)",
          "on-secondary": "var(--jk-on-secondary)",
          "on-secondary-container": "var(--jk-on-secondary-container)",
          tertiary: "var(--jk-tertiary)",
          "tertiary-container": "var(--jk-tertiary-container)",
          "on-tertiary": "var(--jk-on-tertiary)",
          "on-tertiary-container": "var(--jk-on-tertiary-container)",
          error: "var(--jk-error)",
          "on-error": "var(--jk-on-error)",
          "error-container": "var(--jk-error-container)",
          "on-error-container": "var(--jk-on-error-container)",
          outline: "var(--jk-outline)",
          "outline-variant": "var(--jk-outline-variant)",
          "accent-emerald": "var(--jk-accent-emerald)",
          "accent-amber": "var(--jk-accent-amber)",
          "accent-violet": "var(--jk-accent-violet)",
          navy: "var(--jk-navy)",
          "navy-mid": "var(--jk-navy-mid)",
          cyan: "var(--jk-cyan)",
          "cyan-soft": "var(--jk-cyan-soft)",
          "sidebar-bg": "var(--jk-sidebar-bg)",
          "sidebar-bg-end": "var(--jk-sidebar-bg-end)",
        },
      },
      fontFamily: {
        sans: ["var(--font-body)", "ui-sans-serif", "system-ui", "sans-serif"],
        heading: [
          "var(--font-heading)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        body: ["var(--font-body)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        code: ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      borderRadius: {
        sm: "var(--jk-radius-sm)",
        DEFAULT: "var(--jk-radius-default)",
        md: "var(--jk-radius-md)",
        lg: "var(--jk-radius-lg)",
        xl: "var(--jk-radius-xl)",
        full: "var(--jk-radius-full)",
      },
      spacing: {
        "jk-xs": "var(--jk-spacing-xs)",
        "jk-sm": "var(--jk-spacing-sm)",
        "jk-md": "var(--jk-spacing-md)",
        "jk-lg": "var(--jk-spacing-lg)",
        "jk-xl": "var(--jk-spacing-xl)",
        "jk-unit": "var(--jk-spacing-unit)",
        sidebar: "var(--jk-sidebar-width)",
        "sidebar-collapsed": "var(--jk-sidebar-collapsed-width)",
        "header-height": "var(--jk-header-height)",
        "container-max": "var(--jk-container-max)",
        gutter: "var(--jk-gutter)",
      },
      maxWidth: {
        container: "var(--jk-container-max)",
      },
      boxShadow: {
        xs: "var(--jk-shadow-xs)",
        card: "var(--jk-shadow-card)",
        elevated: "var(--jk-shadow-elevated)",
        modal: "var(--jk-shadow-modal)",
        glow: "var(--jk-shadow-glow)",
      },
      backgroundImage: {
        "jk-gradient-primary": "var(--jk-gradient-primary)",
        "jk-gradient-hero": "var(--jk-gradient-hero)",
        "jk-gradient-mesh": "var(--jk-gradient-mesh)",
      },
    },
  },
  plugins: [],
};

export { config };
